version: '3'
services:
  app:
    container_name: food_flow
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
  db:
    container_name: food_flow_db
    restart: always
    image: postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker/db:/var/lib/postgresql/data